def addXAndY():
    x=69
    y=420
    print(x+y)
def jordan():
    print("Jordan")
def gamerMoment():
    print("7 thousand in hitman")
    print("50 thousand pigman")
    print("1+ thousand in New vegas")    
    print("hundreads in RDR2")
    print("500+ in Fallout 4")
def shronk():
    print("Somebody once told me the world is gonna roll me I ain't the sharpest tool in the shed... and I said yep, what a concept I could use a little fuel myself and we all could use a little change")
jordan